# 사용할 수 있는 플레이스 홀더입니다
# <playername> - 플레이어이름
# <online> - 접속자수 / <maxplayer> - 최대플레이어
# <health> - 체력 / <maxhealth> - 최대체력 / <food> - 배고픔
# <level> - 레벨
# <loc:x> - x좌표 / <loc:y> - y좌표 / <loc:z> - z좌표
# <world> - 월드의 이름

# 스코어보드의 제목을 설정합니다.
title: '&b[ &fPRScoreboard &b]'

# 스코어보드의 내용을 설정합니다
# 최대 15개까지 가능합니다 [ 초과 시 출력은 되지 않습니다 ]
# 아무것도 적지 않을 시 한 칸 줄바꿈이 됩니다
scoreboard:
- ''
- '&e:: &f닉네임 &e::'
- '  &f<playername>'
- ''
- '&a:: &f접속자수 &a::'
- '  &f<online>'
- ''

# 설정된 시간(초)마다 스코어보드를 불러옵니다.
loadTime: 1